CREATE DATABASE IF NOT EXISTS coches;
USE coches;
/* TABLA EMPLEADO */
CREATE TABLE EMPLEADO (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DNI VARCHAR(10) NOT NULL UNIQUE,
    JEFE INT,
    CONSTRAINT FK_EMPLEADO_JEFE
        FOREIGN KEY (JEFE)
        REFERENCES EMPLEADO(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

/* TABLA PROYECTO */
CREATE TABLE PROYECTO (
    CODIGO INT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL
);

/* TABLA ASIGNACION */
CREATE TABLE ASIGNACION (
    ID INT,
    CODIGO INT,
    CONSTRAINT PK_ASIGNACION PRIMARY KEY (ID, CODIGO),
    CONSTRAINT FK_ASIGNACION_EMPLEADO
        FOREIGN KEY (ID)
        REFERENCES EMPLEADO(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_ASIGNACION_PROYECTO
        FOREIGN KEY (CODIGO)
        REFERENCES PROYECTO(CODIGO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

/* TABLA VEHICULO */
CREATE TABLE VEHICULO (
    MATRICULA VARCHAR(10) PRIMARY KEY,
    MARCA VARCHAR(20) NOT NULL,
    MODELO VARCHAR(20),
    PERSONA INT,
    CONSTRAINT FK_VEHICULO_PERSONA
        FOREIGN KEY (PERSONA)
        REFERENCES EMPLEADO(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);



/* 1. Eliminar columna MODELO */
ALTER TABLE VEHICULO
DROP COLUMN MODELO;

/* 2. Anadir columna COLOR con valores permitidos */
ALTER TABLE VEHICULO
ADD COLOR VARCHAR(10)
CHECK (COLOR IN ('Blanco', 'Negro', 'Otro'));

/* 3. Anadir columna precio mayor que 1000 */
ALTER TABLE VEHICULO
ADD precio DECIMAL(10,2)
CHECK (precio > 1000);



/* 4. Vaciar la tabla VEHICULO 
DELETE FROM VEHICULO;

/* 5. Eliminar la tabla VEHICULO 
DROP TABLE VEHICULO;*/
